sudo: false
language: node_js
node_js:
  - '0.12'
before_install:
  - 'npm install -g bower grunt-cli'
  - 'gem install compass'
install: npm install
before_script:
 - 'bower install'
notifications:
  slack: teamfuckyeah:myFEHiMWAknnEmBDjCj7AJn3
